[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
    'solmate-utils/=lib/solmate/src/utils/',
    'ds-test/=lib/ds-test/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/'
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config